### ISSUE TITLE
I have a question about this project

### ISSUE THREAD

**Issue by meiguiz** [leobarcellona/FSG-Net#1]
![image](https://github.com/leobarcellona/FSG-Net/assets/90629126/2e86b2c7-4eab-482b-a5eb-9c3f54a64948)
I am confused about the models you mentioned in this section, as I couldn't find where they are located.

**Comment by bach05** [comment]
Hello, 

we opened the link to the pre-trained models. You should be able to download them. If you have any problems, let me know!

Anyway, you can run the training from scratches using our code.
